#ifndef GLOBAL_H
#define GLOBAL_H


enum LogType{SYS,DEV,ERR};
enum DevStatus{ENABLED,DISABLED};
enum CONFIG_TYPE{SERVER_IP,SERVER_PORT,START_DEVID,DEVNUM,C_COMM_MODEL,MQTT_BRUD_RATE,LORA_ADDR,LORA_CHANNEL,
                 S_IP,S_PORT,MQTT_URL,MQTT_USER_NAME,MQTT_PASSWD,S_COMM_MODEL};


enum BUFFER_TYPE{UA_TYPE,WA_TA_TYPE,SIGN_TYPE,VERIFY_RESULT,ENC_MSG};





#endif // GLOBAL_H
